version: "3.9"

services:
  db:
    image: postgres:17.2-alpine
    container_name: trpc-practice-db
    environment:
      POSTGRES_DB: trpc-practice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: